### ISSUE TITLE
Jacob's Quests

### ISSUE THREAD

**Issue by u92gangxfind** [jacob-tucker/Flow-Zero-to-Jacob#24]
https://github.com/emerald-dao/beginner-cadence-course/issues

**Comment by u92gangxfind** [comment]
As if I am going to the first grade, it will be very interesting and fun, successful study for all of us.

**Comment by benbackend** [comment]
Great to have you here.
May I have the link to your repo?

**Comment by u92gangxfind** [comment]
https://floats.city/u92gangx.find?tab=floats   man i in late))))0
