### ISSUE TITLE
Not an actual problem

### ISSUE THREAD

**Issue by foteev** [jacob-tucker/Flow-Zero-to-Jacob#45]
Hello. I've found that we don't need to use quotes while writing TRANSACTION ARGUMENTS. So, may be this is not an actual information in course [readme.md](https://github.com/emerald-dao/beginner-cadence-course/tree/main/chapter2.0/day2#readme) 
Thank you, you're the best.

**Comment by jacob-tucker** [comment]
Thank you very much! I will fix this :D
