### ISSUE TITLE
Issue with Chapter 3, Day 3 Code Example 

### ISSUE THREAD

**Issue by 0xAlighieri** [jacob-tucker/Flow-Zero-to-Jacob#67]
Hello! 

The final code example, of the script transaction that will return the language from the reference appears to generate an error in the flow playground: 

```cadence
import Test from 0x01

pub fun main(): String {
  let ref = Test.getReference(key: "Hello!")
  return ref.language // returns "English"  <--- produces this error: value of type @Test.Greeting? has no member "language". Unknown member.
}
```

I was able to fix it by changing the code to the following: 

```cadence
import Test from 0x01

pub fun main(): String {
  let ref = Test.getReference(key: "Hello!")
  return ref!.language // returns "English"
}
```

**Comment by jacob-tucker** [comment]
Hello! Actually, the code example is correct. I believe you may have a mistake in your `getReference` function. The `getReference` function is supposed to return a non-optional type, so the `!` shouldn't be necessary

**Comment by 0xAlighieri** [comment]
Ah yes, you are right. It appears I am moving t0o quickly and overlooked that modification. 

My apologies, closing. :)
